spring:
  application:
    geocode:
      file:
        path: event/src/main/resources/geocodes.xml
    events:
      dataset:
        refresh: '* * * * * ?'

  mongodb:
    embedded:
      storage:
        database-dir: ./.db

  profiles:
    active: load_geocode_config