spring:
  profiles:
    active: load_geocode_config
    include:
      - oauth2
  application:
    geocode:
      file:
        path: event/src/main/resources/geocodes.xml
    events:
      dataset:
        refresh: '0 0 0 * * ?'

  mongodb:
    embedded:
      storage:
        database-dir: ./.db

logging:
  level:
    root: info
    org.springframework: trace
    org.springframework.security: trace
