spring:
  profiles:
    active: default
    include:
      - oauth2
      - view
  application:
    geocode:
      file:
        path: event/src/main/resources/geocodes.xml
    events:
      dataset:
        refresh: '0 0 0 * * ?'

  mongodb:
    embedded:
      storage:
        database-dir: ./.db

logging:
  level:
    root: info
    org.springframework: info
    org.springframework.security: info
