spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 123.apps.googleusercontent.com
            client-secret: 321
            scope: profile,email
        provider:
          google:
            userNameAttribute: email
    user:
      password: '0716'
      name: seko

